import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Button, ChakraProvider, Flex, Text, Image } from '@chakra-ui/react'
import { theme } from '@/app/theme'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Header() {
  return (
    <Flex as='header' shadow='md' background='white' justifyContent='center' height='64px'>
      <Flex width='1280px' alignItems='center' margin='32px' background='blue'>
        <Link style={{ height: '64px', display: 'flex', alignItems: 'center' }} href='/'>
          <Image width='40px' height='40px' borderRadius='10px' src='/pixapencil-logo.jpg' />
          <Text marginLeft='16px'>PixaPencil</Text>
        </Link>

        <Flex marginLeft='auto' gap='32px'>
          <Link href='/'>Docs</Link>
          <Link href='/blog'>Blog</Link>
          <Link href='/'>Community</Link>
        </Flex>

        <Button colorScheme='messenger' marginLeft='32px'>
          Star on GitHub
        </Button>
      </Flex>
    </Flex>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ChakraProvider theme={theme}>
          <Flex flexDirection='column' height='100vh' /*overflow="clip"*/>
            <Header />
            {children}
          </Flex>
        </ChakraProvider>
      </body>
    </html>
  )
}
