package com.realtomjoney.pyxlmoose.utility

object StringConstants {
    const val APP_NAME = "PyxlMoose"

    const val SPAN_COUNT_EXTRA = "SPAN_COUNT"
    const val PROJECT_TITLE_EXTRA = "PROJECT_TITLE"

    const val INDEX_EXTRA = "INDEX"

    const val DIALOG_POSITIVE_BUTTON_TEXT = "OK"
    const val DIALOG_NEGATIVE_BUTTON_TEXT = "Cancel"

    const val DIALOG_CLEAR_CANVAS_TITLE = "Clear canvas"
    const val DIALOG_CLEAR_CANVAS_MESSAGE = "Are you sure you want to clear the canvas?"

    const val FRAGMENT_FIND_AND_REPLACE_TITLE = "Find and Replace"
    const val FRAGMENT_COLOR_PICKER_TITLE = "Select Color"
    const val FRAGMENT_NEW_COLOR_PALETTE_TITLE = "New Color Palette"

    const val COLOR_FILTER_IDENTIFIER = "COLOR_FILTER"
    const val DARKEN_FILTER_IDENTIFIER = "DARKEN_FILTER"
    const val LIGHTEN_FILTER_IDENTIFIER = "LIGHTEN_FILTER"
    const val INVERT_FILTER_IDENTIFIER = "INVERT_FILTER"
    const val INVERT_RED_FILTER_IDENTIFIER = "INVERT_RED_FILTER"
    const val INVERT_GREEN_FILTER_IDENTIFIER = "INVERT_GREEN_FILTER"
    const val INVERT_BLUE_FILTER_IDENTIFIER = "INVERT_BLUE_FILTER"
    const val GRAYSCALE_FILTER_IDENTIFIER = "GRAYSCALE_FILTER"
    const val GRAYSCALE_FILTER_TWO_IDENTIFIER = "GRAYSCALE_FILTER_TWO"
    const val GRAYSCALE_FILTER_THREE_IDENTIFIER = "GRAYSCALE_FILTER_THREE"

    const val PENCIL_TOOL_IDENTIFIER = "PENCIL"
    const val VERTICAL_MIRROR_TOOL_IDENTIFIER = "VERTICAL_MIRROR"
    const val HORIZONTAL_MIRROR_TOOL_IDENTIFIER = "HORIZONTAL_MIRROR"
    const val DARKEN_TOOL_IDENTIFIER = "DARKEN"
    const val LIGHTEN_TOOL_IDENTIFIER = "LIGHTEN"
    const val CLEAR_CANVAS_TOOL_IDENTIFIER = "CLEAR_CANVAS"
    const val CHANGE_BACKGROUND_TOOL_IDENTIFIER = "CHANGE_BACKGROUND"
    const val COLOR_PICKER_TOOL_IDENTIFIER = "COLOR_PICKER"
    const val FIND_AND_REPLACE_TOOL_IDENTIFIER = "FIND_AND_REPLACE"
    const val ERASE_TOOL_IDENTIFIER = "ERASE"
    const val GRID_TOOL_IDENTIFIER = "GRID"
}