package com.realtomjoney.pyxlmoose.utility

object StringConstants {
    const val APP_NAME = "PyxlMoose"

    const val TAB_STARRED_TITLE = "Starred"

    const val SPAN_COUNT_EXTRA = "SPAN_COUNT"
    const val PROJECT_TITLE_EXTRA = "PROJECT_TITLE"

    const val INDEX_EXTRA = "INDEX"

    const val DIALOG_POSITIVE_BUTTON_TEXT = "OK"
    const val DIALOG_NEGATIVE_BUTTON_TEXT = "Cancel"

    const val DIALOG_CLEAR_CANVAS_TITLE = "Clear canvas"
    const val DIALOG_CLEAR_CANVAS_MESSAGE = "Are you sure you want to clear the canvas?"
    const val DIALOG_UNSAVED_CHANGES_TITLE = "Unsaved changes"
    const val DIALOG_UNSAVED_CHANGES_MESSAGE = "You have unsaved changes, are you sure you want to exit?"

    const val FRAGMENT_FIND_AND_REPLACE_TITLE = "Find and Replace"
    const val FRAGMENT_COLOR_PICKER_TITLE = "Select Color"
    const val FRAGMENT_NEW_COLOR_PALETTE_TITLE = "New Color Palette"

    const val COLOR_FILTER_IDENTIFIER = "COLOR_FILTER"
    const val DARKEN_FILTER_IDENTIFIER = "DARKEN_FILTER"
    const val LIGHTEN_FILTER_IDENTIFIER = "LIGHTEN_FILTER"
    const val INVERT_FILTER_IDENTIFIER = "INVERT_FILTER"
    const val INVERT_RED_FILTER_IDENTIFIER = "INVERT_RED_FILTER"
    const val INVERT_GREEN_FILTER_IDENTIFIER = "INVERT_GREEN_FILTER"
    const val INVERT_BLUE_FILTER_IDENTIFIER = "INVERT_BLUE_FILTER"
    const val GRAYSCALE_FILTER_IDENTIFIER = "GRAYSCALE_FILTER"

    const val PENCIL_TOOL_IDENTIFIER = "PENCIL"
    const val FILL_TOOL_IDENTIFIER = "FILL"
    const val VERTICAL_MIRROR_TOOL_IDENTIFIER = "VERTICAL_MIRROR"
    const val HORIZONTAL_MIRROR_TOOL_IDENTIFIER = "HORIZONTAL_MIRROR"
    const val LINE_TOOL_IDENTIFIER = "LINE"
    const val RECTANGLE_TOOL_IDENTIFIER = "RECTANGLE"
    const val OUTLINED_RECTANGLE_TOOL_IDENTIFIER = "OUTLINED_RECTANGLE"
    const val DARKEN_TOOL_IDENTIFIER = "DARKEN"
    const val LIGHTEN_TOOL_IDENTIFIER = "LIGHTEN"
    const val CLEAR_CANVAS_TOOL_IDENTIFIER = "CLEAR_CANVAS"
    const val COLOR_PICKER_TOOL_IDENTIFIER = "COLOR_PICKER"
    const val FIND_AND_REPLACE_TOOL_IDENTIFIER = "FIND_AND_REPLACE"
    const val ERASE_TOOL_IDENTIFIER = "ERASE"
    const val GRID_TOOL_IDENTIFIER = "GRID"

    const val SHARED_PREF_PIXEL_PERFECT = "PIXEL_PERFECT"
}